Repository apache/rocketmq-client-go, pull requests merged in 2019-09, with the labels that each got.

#191 [ISSUE #190] Modify some code to be more elegant.
  consumer/consumer.go
  consumer/process_queue.go
  internal/utils/files.go
  primitive/result.go
Labels: enhancement

#189 [ISSUE #188]fix consumer example & remove extra file
  .DS_Store
  examples/consumer/acl/main.go
  examples/consumer/broadcast/main.go
  examples/consumer/delay/main.go
  examples/consumer/namespace/main.go
  examples/consumer/orderly/main.go
  examples/consumer/retry/concurrent/main.go
  examples/consumer/simple/main.go
  examples/consumer/strategy/main.go
  examples/consumer/trace/main.go
Labels: enhancement

#187 [ISSUE #186] Fix offsetSotre
  consumer/offset_store.go
  consumer/offset_store_test.go
Labels: enhancement

#193 [ISSUE #192]Refactor MessageSelector
  primitive/message.go
  producer/producer.go
  producer/producer_test.go
  producer/selector.go
  producer/selector_test.go
Labels: discuss

#196 Fix the domain checker was rollback before
  primitive/base.go
Labels: enhancement

#199 [ISSUE #184]Fix errors of using internal codes in the exported snippet
  errors.go
  examples/consumer/pull/main.go
  internal/utils/errors.go
Labels: bug

#197 [ISSUE #166] Make Access Message.Properties thread safety
  consumer/consumer.go
  consumer/process_queue.go
  consumer/push_consumer.go
  examples/consumer/simple/main.go
  examples/producer/acl/main.go
  examples/producer/async/main.go
  examples/producer/delay/main.go
  examples/producer/interceptor/main.go
  examples/producer/namespace/main.go
  examples/producer/simple/main.go
  examples/producer/tag/main.go
  examples/producer/trace/main.go
  internal/client.go
  internal/trace.go
  primitive/message.go
  primitive/result_test.go
  producer/producer.go
  producer/producer_test.go
Labels: bug

#200 [ISSUE #185] Fix errors of comments and spelling
  consumer/push_consumer.go
  examples/consumer/retry/concurrent/main.go
  primitive/ctx.go
Labels: enhancement

#206 [ISSUE #183] add set consumeMessageBatchMaxSize and fixed count++ skip one message…
  consumer/option.go
  consumer/push_consumer.go
Labels: bug, enhancement

#214 doc(Readme):modify the install method of c library
  doc/Introduction.md
Labels: doc

#216 Support lite order producer
  core/api.go
  core/producer.go
Labels: enhancement

#218 fix(produer):remove cycle package
  core/producer.go
Labels: bug

#219 feat(demos): add separately demos
  demos/orderly_push_consumer.go
  demos/producer.go
  demos/producer_orderly.go
  demos/push_consumer.go
Labels: enhancement

#208 [ISSUE #201]Change default consumer option to Clustering
  consumer/option.go
  consumer/push_consumer_test.go
Labels: enhancement

#215 fixed log function
  consumer/push_consumer.go
Labels: bug

#225 feat(consumer): add set maxcachesize api to support simple flow-control
  core/api.go
  core/push_consumer.go
Labels: enhancement
