Repository apache/rocketmq-client-go, pull requests merged in 2019-12, with the labels that each got.

#320 [ISSUE #318] fix: using atomic status for producer/consumer
  consumer/consumer.go
  consumer/pull_consumer.go
  consumer/push_consumer.go
  internal/model.go
  producer/producer.go
Labels: enhancement

#324 [ISSUE #323] feat(message): remove extra code
  primitive/message.go
Labels: enhancement

#325 [ISSUE #328] message add GetProperties func
  primitive/message.go
  primitive/result_test.go
Labels: enhancement

#316 [ISSUE #313] feat(client): add mutex for rebalance
  consumer/consumer.go
  consumer/process_queue.go
  internal/client.go
Labels: enhancement

#319 [ISSUE #317] fix(message): 错误的 equals实现
  consumer/consumer.go
  primitive/message.go
Labels: bug

#322 [ISSUE #321] fix: lots of incorrect impl
  consumer/consumer.go
  consumer/push_consumer.go
Labels: bug

#315 [ISSUE #314] support name server domain
  consumer/consumer.go
  consumer/option.go
  internal/client.go
  internal/mock_namesrv.go
  internal/namesrv.go
  internal/namesrv_test.go
Labels: enhancement

#333 [ISSUE #334] feat(core): fix concurrent read/write for broker version
  internal/client.go
  internal/namesrv.go
  internal/route.go
  internal/route_test.go
Labels: bug

#336 [ISSUE #335] feat(example): rename shutdown instead of shundown
  examples/consumer/retry/order/main.go
  examples/consumer/simple/main.go
  examples/consumer/strategy/main.go
  examples/consumer/tag/main.go
  examples/consumer/trace/main.go
  examples/producer/acl/main.go
  examples/producer/async/main.go
  examples/producer/delay/main.go
  examples/producer/interceptor/main.go
  examples/producer/namespace/main.go
  examples/producer/simple/main.go
  examples/producer/tag/main.go
  examples/producer/trace/main.go
  examples/producer/transaction/main.go
Labels: doc

#339 [ISSUE #338] fix(route): update route
  internal/client.go
  internal/mock_client.go
  internal/mock_namesrv.go
  internal/namesrv.go
  internal/route.go
  producer/producer.go
Labels: bug
