Repository apache/rocketmq-client-go, pull requests merged in 2020-04, with the labels that each got.

#472 [ISSUE #471] The message mode, ctype and where was wrong in the heartbeat data
  consumer/push_consumer.go
  internal/client.go
Labels: bug

#457 feat: support nameserver resolver
  .travis.yml
  api.go
  consumer/consumer.go
  consumer/mock_offset_store.go
  consumer/offset_store.go
  consumer/option.go
  consumer/pull_consumer.go
  consumer/push_consumer.go
  consumer/push_consumer_test.go
  consumer/strategy_test.go
  examples/consumer/acl/main.go
  examples/consumer/broadcast/main.go
  examples/consumer/delay/main.go
  examples/consumer/interceptor/main.go
  examples/consumer/namespace/main.go
  examples/consumer/orderly/main.go
  examples/consumer/pull/main.go
  examples/consumer/retry/concurrent/main.go
  examples/consumer/retry/order/main.go
  examples/consumer/simple/main.go
  examples/consumer/strategy/main.go
  examples/consumer/tag/main.go
  examples/consumer/trace/main.go
  examples/producer/acl/main.go
  examples/producer/async/main.go
  examples/producer/batch/main.go
  examples/producer/delay/main.go
  examples/producer/interceptor/main.go
  examples/producer/namespace/main.go
  examples/producer/simple/main.go
  examples/producer/tag/main.go
  examples/producer/trace/main.go
  examples/producer/transaction/main.go
  internal/client.go
  internal/mock_namesrv.go
  internal/model.go
  internal/namesrv.go
  internal/namesrv_test.go
  internal/remote/codec.go
  internal/remote/codec_test.go
  internal/remote/mock_remote_client.go
  internal/route_test.go
  internal/trace.go
  primitive/base.go
  primitive/base_test.go
  primitive/nsresolver.go
  primitive/nsresolver_test.go
  producer/option.go
  producer/producer.go
  producer/producer_test.go
Labels: discuss, enhancement

#474 [ISSUE #473] support nsresolver in TraceConfig
  examples/consumer/trace/main.go
  examples/producer/trace/main.go
  internal/trace.go
  primitive/trace.go
Labels: enhancement
