Repository apache/rocketmq-client-go, pull requests merged in 2020-01, with the labels that each got.

#350 [ISSUE #349] fix: pull timeout and suspend time is not consistent with java
  consumer/push_consumer.go
  internal/client.go
  internal/request.go
Labels: bug

#363 feat: more consumer option config
  consumer/option.go
Labels: enhancement

#359 [ISSUE #358] feat: rename persistent with interval
  internal/client.go
Labels: doc

#353 [ISSUE #352]feat: use jsoniter to replace with json
  consumer/consumer.go
  consumer/offset_store.go
  go.mod
  go.sum
  internal/model.go
  internal/remote/codec.go
  internal/remote/codec_test.go
  internal/route.go
Labels: enhancement

#351 [ISSUE #344] feat(client): advance timeout
  internal/client.go
  internal/mock_client.go
  internal/mock_namesrv.go
  internal/remote/future.go
  internal/remote/mock_remote_client.go
  internal/remote/remote_client.go
  internal/remote/remote_client_test.go
  internal/route.go
  internal/route_test.go
  internal/trace.go
  producer/producer.go
  producer/producer_test.go
Labels: enhancement

#361 [ISSUE #360] feat: use pool for header codec
  internal/remote/remote_client.go
  primitive/pool.go
Labels: enhancement

#367 [ISSUE #366] feat: remove extra code
  internal/remote/future.go
  internal/remote/remote_client.go
  internal/remote/remote_client_test.go
Labels: doc

#357 [ISSUE #356] feat(consumer): redesign stat
  consumer/statistics.go
Labels: enhancement

#373 [ISSUE #340] change transaction producer interface signature
  examples/producer/transaction/main.go
  internal/callback.go
  internal/client.go
  primitive/message.go
  producer/producer.go
Labels: enhancement

#372 [ISSUE #371]feat: clean extra code for internal packagec
  consumer/push_consumer.go
  internal/client.go
  internal/mock_client.go
  internal/route.go
  internal/validators.go
  producer/producer.go
  producer/producer_test.go
Labels: doc

#355 [ISSUE #354] feat: Support PanicHandler
  consumer/push_consumer.go
  consumer/statistics.go
  errors.go
  internal/client.go
  internal/remote/remote_client.go
  internal/trace.go
  internal/utils/fun.go
  primitive/base.go
  producer/producer.go
Labels: enhancement

#375 fix(doc): update notice and open statistic label
  NOTICE
  README.md
Labels: doc, enhancement

#378 fix(doc): update notice and open statistic label
  NOTICE
  README.md
  changelog
Labels: doc

#387 fix: consume type compatible with protocol
  consumer/consumer.go
Labels: bug

#385 Update go.mod
  docs/Introduction.md
  go.mod
Labels: doc
