Repository apache/rocketmq-client-go, pull requests merged in 2020-02, with the labels that each got.

#403 [ISSUE #402] fix(consumer): improve retry topic support
  consumer/consumer.go
  consumer/push_consumer.go
  internal/client.go
Labels: enhancement

#392 [ISSUE #391] feat: support mq error
  primitive/errors.go
Labels: enhancement

#412 feat(doc): update SDK install docs
  doc/Introduction.md
Labels: doc

#420 fix(strategy): change the deafult mq sort to ASC when do rebalance.
  consumer/consumer.go
Labels: bug

#414 fix(consumer): use sync offset fix instead if async
  consumer/push_consumer.go
Labels: enhancement

#422 fix(travisci): use archive server to avoid download rocketmq package failed
  .travis.yml
Labels: test

#418 [ISSUE #417] fix(consumer): sub info not updated when scale out queue
  internal/client.go
Labels: bug

#425 doc(readme): add Due Diligence link in the readme file
  README.md
Labels: doc

#408 [ISSUE #407] feat: reuse bytes.Buffer
  primitive/message.go
  primitive/pool.go
  primitive/result_test.go
Labels: discuss

#416 [ISSUE #415] feat(producer): auto create topic for producer
  examples/producer/simple/main.go
  internal/client.go
  internal/mock_namesrv.go
  internal/namesrv.go
  internal/route.go
  primitive/errors.go
  producer/option.go
  producer/producer.go
Labels: enhancement

#436 fix(producer): update name server address immediately when client start
  internal/client.go
Labels: bug
