Repository apache/rocketmq-client-go, pull requests merged in 2021-03, with the labels that each got.

#607 feat(produce) : reduce memory copy for on-wire protocol
  internal/remote/codec.go
  internal/remote/remote_client.go
  internal/remote/tcp_conn.go
Labels: enhancement

#616 [ISSUE #615]fix: putmessage should check msg in consumingMsgOrderlyTreeMap
  consumer/process_queue.go
Labels: bug

#608 feat(produce): support message compression
  internal/utils/compression.go
  internal/utils/compression_test.go
  internal/utils/helper_test.go
  internal/utils/net.go
  primitive/message.go
  producer/option.go
  producer/producer.go
Labels: enhancement

#597 [ISSUE #596] Fix command register conflict, add consumer and producer logic code
  benchmark/consumer.go
  benchmark/producer.go
Labels: bug, test
