Repository apache/rocketmq-client-go, pull requests merged in 2022-08, with the labels that each got.

#879 [ISSUE #878] Clean expired message in CLUSTERING model for push_consumer
  consumer/option.go
  consumer/process_queue.go
  consumer/push_consumer.go
Labels: enhancement

#880 [ISSUE #882] keep queryTopicRouteInfoFromServer timeout the same as Java
  internal/route.go
Labels: enhancement

#885 [ISSUE #884]fix goroutine leak
  consumer/push_consumer.go
  consumer/push_consumer_test.go
Labels: enhancement

#886 [feat] fix query not found
  consumer/offset_store.go
  internal/response.go
Labels: enhancement

#881 feat: support lite pull consumer
  .travis.yml
  admin/admin.go
  api.go
  consumer/consumer.go
  consumer/option.go
  consumer/pull_consumer.go
  consumer/strategy.go
  examples/consumer/pull/main.go
  examples/consumer/pull/poll/main.go
  examples/consumer/pull/pull/main.go
  examples/consumer/pull/pull_from/main.go
  go.mod
  go.sum
  internal/utils/namespace.go
  internal/utils/string.go
  primitive/result.go
  rlog/log.go
Labels: enhancement

#893 [ISSUE #862]Update readme file according to the new features in the latest release version.
  README.md
Labels: doc

#891 [ISSUE #894](feat): add filter hooks in consumer.
  consumer/consumer.go
  consumer/option.go
  go.mod
  hooks/filter_message_hook.go
Labels: enhancement, discuss

#846 [ISSUE #845] support standard json
  internal/route.go
Labels: enhancement, discuss

#902 [ISSUE #901]Close the traceDispatcher when producer or consumer is shutdown
  consumer/interceptor.go
  consumer/option.go
  consumer/push_consumer.go
  producer/interceptor.go
  producer/option.go
  producer/producer.go
Labels: enhancement
