Repository apache/rocketmq-client-go, pull requests merged in 2022-07, with the labels that each got.

#773 fix(sendOneWay): fix stack overflow caused by recursive calls
  producer/producer.go
Labels: bug

#852 bugfix rebalance is not paused after suspend and rebalance not trigge…
  consumer/consumer.go
  consumer/push_consumer.go
  internal/client.go
Labels: bug

#820 [ISSUE #819] Fix sis.samplingInSeconds and sis.printAtMinutes() running in different goroutines cause DATA RACE
  consumer/statistics.go
  consumer/statistics_test.go
Labels: enhancement

#783 Maybe can remove some useless code in encodeBatch()
  producer/producer.go
Labels: codestyle

#812 [ISSUE #813] Fix bug when get `mqadmin consumerStatus` can't get consume status.
  consumer/push_consumer.go
Labels: bug

#854 a liitle improvement use chan instead
  examples/consumer/simple/main.go
Labels: good first issue

#860 [ISSUE #797] Fix msg lost if consumer crash when send msg back failed.
  consumer/push_consumer.go
Labels: bug

#859 [ISSUE #754] close msgCh when pq droped
  consumer/process_queue.go
Labels: enhancement

#865 [ISSUE #780]avoid sendmessage back with origin message body in request.
  consumer/push_consumer.go
Labels: enhancement

#729 [ISSUE #728] client shutdown abnormally
  errors/errors.go
  internal/client.go
  producer/producer.go
Labels: enhancement

#868 [ISSUE #864] update rlog to 1.9.0 to fix CVE-2022-29526 in golang.org/x/sys
  go.mod
  go.sum
Labels: enhancement

#867 [ISSUE #869] Fix: Consumer api comments
  api.go
Labels: doc

#871 [ISSUE #870] add license header for some new files.
  consumer/message_util.go
  examples/consumer/rpc/main.go
  examples/producer/rpc/async/main.go
  examples/producer/rpc/sync/main.go
  go.mod
  go.sum
  internal/request_response_future.go
Labels: codestyle

#873 [ISSUE #872] fix code coverage shell error in travis ci yml.
  .travis.yml
Labels: enhancement

#863 [ISSUE #876] Safely checking context in trace producer.
  primitive/ctx.go
  producer/interceptor.go
  producer/producer.go
Labels: enhancement
